version: 2

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
            key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
#  test:
#    docker:
#      - image: cimg/openjdk:11.0
#    steps:
#      - checkout
#      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
#      - test