version: 2.1

orbs:
  maven: circleci/maven@1.3.0

executors:
  openjdk11:
    docker:
      - image: cimg/openjdk:11.0

workflows:
  build_and_test:
    jobs:
      - maven/test
          executor: openjdk11